image: Visual Studio 2017
configuration: Release
platform: Any CPU

# Don't build un-tagged commits
skip_non_tags: true

# Don't get the full project history to save time
shallow_clone: true

# Cache NuGet packages between builds to save time
cache:
  - packages -> **\packages.config

# Auto-fill AssemblyInfo.cs
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  # Use tag name + build number as assembly version
  # Assembly versions should be Major.Minor.Revision.Build
  # ex: 1.1.12.255
  assembly_version: '$(APPVEYOR_REPO_TAG_NAME).$(APPVEYOR_BUILD_NUMBER)'
  assembly_file_version: '$(APPVEYOR_REPO_TAG_NAME).$(APPVEYOR_BUILD_NUMBER)'
  assembly_informational_version: '$(APPVEYOR_REPO_TAG_NAME).$(APPVEYOR_BUILD_NUMBER)'

before_build:
# Manually set build version in a way that allows environment variables
- ps: >-
    if (-not (Test-Path env:APPVEYOR_REPO_TAG_NAME)) { $env:APPVEYOR_REPO_TAG_NAME = "0.0.0" }
    Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER"

# Generate a VERSION file to include in artifacts
- ps: >-
    $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
    
    "source: $env:APPVEYOR_REPO_PROVIDER $env:APPVEYOR_REPO_NAME" > VERSION
    
    "commit: $env:APPVEYOR_REPO_BRANCH $env:GIT_HASH $env:APPVEYOR_REPO_COMMIT_TIMESTAMP" >> VERSION
    
    "version: $env:APPVEYOR_BUILD_VERSION" >> VERSION

# Restore NuGet packages
- appveyor-retry nuget restore

build:
  project: PulsarPluginLoader.sln
  verbosity: minimal
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  use_snupkg_format: true

after_build:
# Create two .ZIP artifacts:
#   PulsarPluginBootstrapper-*.zip for end users to enable plugins (recommended download)
#   PulsarPluginLoader.dll-*.zip for developers to reference during plugin creation
- cmd: >-
    7z a PulsarPluginBootstrapper-%APPVEYOR_BUILD_VERSION%-%GIT_HASH%.zip README.md VERSION .\PulsarInjector\bin\Release\* -xr!*.pdb -mx=7

    7z a PulsarPluginLoader.dll-%APPVEYOR_BUILD_VERSION%-%GIT_HASH%.zip README.md VERSION .\PulsarPluginLoader\bin\Release\PulsarPluginLoader.dll -mx=7

artifacts:
- path: PulsarPluginBootstrapper-$(APPVEYOR_BUILD_VERSION)-$(GIT_HASH).zip
  name: PulsarPluginBootstrapper
- path: PulsarPluginLoader.dll-$(APPVEYOR_BUILD_VERSION)-$(GIT_HASH).zip
  name: PulsarPluginLoader.dll

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: PPL v$(APPVEYOR_BUILD_VERSION)
  description: ""
  artifact: PulsarPluginBootstrapper,PulsarPluginLoader.dll
  # Only upload TAGGED releases instead of every commit
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: nJm0eDjrcfLhUCTsM7AiTp7GJi40mWXB8LPFRHek/uMqcvX2mdxxZ8cusuns5GAO

- provider: NuGet
  api_key:
    secure: 0YXNLjpjRQ0+OADwFJWdyMFDN4tfOR0G4Kxzx3AE/UCLmkXbx+Z00pi1XhQqClRL
  skip_symbols: false
  artifact: /.*\.nupkg/